export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  FEED: '/feed',
  TRENDING: '/trending',
  POST_DETAIL: '/post/:id',
  PUBLIC_PROFILE: '/profile/:uid',
  EDIT_PROFILE: '/profile/edit',
  NEARBY: '/nearby',
  SETTINGS: '/settings',
  DASHBOARD: '/dashboard',
  USER_TASKS: '/dashboard/tasks',
  USER_NOTES: '/dashboard/notes',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_TASKS: '/admin/tasks',
  ADMIN_NOTES: '/admin/notes',
};
